/*
 * Interface.java
 *
 * Created on __DATE__, __TIME__
 */

package USTC_Clotho_App;

/**
 *
 * @author  __USER__
 */
public class Interface extends javax.swing.JFrame {

	/** Creates new form Interface */
	public Interface() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		regulatorScrollPane = new javax.swing.JScrollPane();
		regulatorTable = new javax.swing.JTable();
		regulatorNameLabel = new javax.swing.JLabel();
		regulatorName = new javax.swing.JTextField();
		regulateeCanScrollPane = new javax.swing.JScrollPane();
		regulateeCandidates = new javax.swing.JTable();
		pictureLabel = new javax.swing.JLabel();
		regulateeNameLabel = new javax.swing.JLabel();
		regulateeName = new javax.swing.JTextField();
		regulatorCanScrollPane = new javax.swing.JScrollPane();
		regulatorCandidates = new javax.swing.JTable();
		regulateeScrollPane = new javax.swing.JScrollPane();
		regulateeTable = new javax.swing.JTable();
		searchBt = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);

		regulatorScrollPane.setBackground(new java.awt.Color(255, 255, 255));
		regulatorScrollPane.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		regulatorScrollPane.setForeground(new java.awt.Color(204, 204, 204));
		regulatorScrollPane.setViewportBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		regulatorTable.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		regulatorTable.setFont(new java.awt.Font("Consolas", 0, 12));
		regulatorTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		regulatorTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		regulatorTable.setGridColor(new java.awt.Color(204, 204, 204));
		regulatorTable
				.setSelectionBackground(new java.awt.Color(204, 204, 204));
		regulatorScrollPane.setViewportView(regulatorTable);

		regulatorNameLabel.setFont(new java.awt.Font("Consolas", 1, 14));
		regulatorNameLabel.setLabelFor(regulatorName);
		regulatorNameLabel.setText("jLabel1");
		regulatorNameLabel.setOpaque(true);

		regulatorName.setFont(new java.awt.Font("Courier New", 0, 12));
		regulatorName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				regulatorNameActionPerformed(evt);
			}
		});

		regulateeCanScrollPane.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(204, 204, 204), 1, true));
		regulateeCanScrollPane.setForeground(new java.awt.Color(204, 204, 204));
		regulateeCanScrollPane.setViewportBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		regulateeCandidates.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		regulateeCandidates.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		regulateeCandidates
				.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		regulateeCandidates.setGridColor(new java.awt.Color(102, 102, 102));
		regulateeCandidates.setSelectionBackground(new java.awt.Color(204, 204,
				204));
		regulateeCanScrollPane.setViewportView(regulateeCandidates);

		pictureLabel.setText("picture");

		regulateeNameLabel.setFont(new java.awt.Font("Consolas", 1, 14));
		regulateeNameLabel.setLabelFor(regulatorName);
		regulateeNameLabel.setText("jLabel1");
		regulateeNameLabel.setOpaque(true);

		regulateeName.setFont(new java.awt.Font("Courier New", 0, 12));

		regulatorCanScrollPane.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(204, 204, 204), 1, true));
		regulatorCanScrollPane.setForeground(new java.awt.Color(204, 204, 204));
		regulatorCanScrollPane.setViewportBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		regulatorCandidates.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		regulatorCandidates.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		regulatorCandidates
				.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		regulatorCandidates.setGridColor(new java.awt.Color(204, 204, 204));
		regulatorCandidates.setSelectionBackground(new java.awt.Color(204, 204,
				204));
		regulatorCanScrollPane.setViewportView(regulatorCandidates);

		regulateeScrollPane.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		regulateeScrollPane.setForeground(new java.awt.Color(204, 204, 204));

		regulateeTable.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		regulateeTable.setFont(new java.awt.Font("Consolas", 0, 12));
		regulateeTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		regulateeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		regulateeTable.setGridColor(new java.awt.Color(204, 204, 204));
		regulateeTable
				.setSelectionBackground(new java.awt.Color(102, 102, 102));
		regulateeScrollPane.setViewportView(regulateeTable);

		searchBt.setBackground(new java.awt.Color(153, 153, 153));
		searchBt.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 14));
		searchBt.setText("Search!");
		searchBt.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		searchBt.setOpaque(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(51, 51, 51)
								.addComponent(regulatorScrollPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										128,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(7, 7, 7)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						regulateeCanScrollPane,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						159,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(62,
																						62,
																						62)
																				.addComponent(
																						regulatorNameLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						78,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(
														regulatorName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														115,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														searchBt,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														100, Short.MAX_VALUE)
												.addComponent(
														pictureLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														100,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(22, 22,
																		22)
																.addComponent(
																		regulateeNameLabel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		93,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(44, 44,
																		44))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		regulatorCanScrollPane,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		159,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														regulateeName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														115,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(regulateeScrollPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										114,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(54, 54, 54)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGap(34, 34,
																		34)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						regulatorNameLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						27,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						regulateeNameLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						27,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						regulatorName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						37,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						pictureLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						regulateeName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						37,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(21,
																										21,
																										21)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														regulatorCanScrollPane,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														287,
																														Short.MAX_VALUE)
																												.addComponent(
																														regulateeCanScrollPane,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														287,
																														Short.MAX_VALUE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(33,
																										33,
																										33)
																								.addComponent(
																										searchBt,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										100,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		regulateeScrollPane,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		regulatorScrollPane,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		398,
																		Short.MAX_VALUE)))
								.addGap(27, 27, 27)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void regulatorNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Interface JFrame = new Interface();
				JFrame.setVisible(true);
				System.out.print(JFrame.getHeight() + "\t" + JFrame.getWidth());
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel pictureLabel;
	private javax.swing.JScrollPane regulateeCanScrollPane;
	private javax.swing.JTable regulateeCandidates;
	private javax.swing.JTextField regulateeName;
	private javax.swing.JLabel regulateeNameLabel;
	private javax.swing.JScrollPane regulateeScrollPane;
	private javax.swing.JTable regulateeTable;
	private javax.swing.JScrollPane regulatorCanScrollPane;
	private javax.swing.JTable regulatorCandidates;
	private javax.swing.JTextField regulatorName;
	private javax.swing.JLabel regulatorNameLabel;
	private javax.swing.JScrollPane regulatorScrollPane;
	private javax.swing.JTable regulatorTable;
	private javax.swing.JButton searchBt;
	// End of variables declaration//GEN-END:variables

}