/*
 * mainPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package USTC_Clotho_App;

/**
 *
 * @author  __USER__
 */
public class mainPanel extends javax.swing.JPanel {

	/** Creates new form mainPanel */
	public mainPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		USTClogo = new javax.swing.JLabel();
		matrixScrollPane = new javax.swing.JScrollPane();
		inputMatrixTable = new javax.swing.JTable();
		matrixSizeLabel = new javax.swing.JLabel();
		sizeInput = new javax.swing.JTextField();
		commitSizeBt = new javax.swing.JButton();
		modeOneLabel = new javax.swing.JLabel();
		modeTwoLabel = new javax.swing.JLabel();
		modeOneBt = new javax.swing.JButton();
		modeTwoBt = new javax.swing.JButton();

		USTClogo.setText("USTC_Software");

		inputMatrixTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		inputMatrixTable.setRowHeight(25);
		inputMatrixTable.setSelectionBackground(new java.awt.Color(204, 204,
				204));
		matrixScrollPane.setViewportView(inputMatrixTable);

		matrixSizeLabel.setText("Matrix Size");

		sizeInput.setText("jTextField1");

		commitSizeBt.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 12));
		commitSizeBt.setText("commit");
		commitSizeBt.setToolTipText("Press This to commit matrix size");
		commitSizeBt.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(204, 204, 204), 1, true));
		commitSizeBt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				commitSizeBtActionPerformed(evt);
			}
		});

		modeOneLabel.setText("Using Operon-Operon");

		modeTwoLabel.setText("Using Gene-Promoter");

		modeOneBt.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 12));
		modeOneBt.setText("Mode 1");
		modeOneBt
				.setToolTipText("Press it to search in Operon-Operon database");
		modeOneBt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				modeOneBtActionPerformed(evt);
			}
		});

		modeTwoBt.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 12));
		modeTwoBt.setText("Mode 2");
		modeTwoBt.setToolTipText("Press it to search in Gene-Promter database");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(53, 53,
																		53)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(37,
																										37,
																										37)
																								.addComponent(
																										matrixSizeLabel)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										sizeInput,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										83,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										commitSizeBt,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										95,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						USTClogo,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						450,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						matrixScrollPane)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(87,
																										87,
																										87)
																								.addComponent(
																										modeOneBt))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(65,
																										65,
																										65)
																								.addComponent(
																										modeOneLabel,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										140,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		123,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										modeTwoLabel)
																								.addGap(50,
																										50,
																										50))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										modeTwoBt)
																								.addGap(74,
																										74,
																										74)))))
								.addContainerGap(32,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(USTClogo,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										90,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														commitSizeBt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														27,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														sizeInput,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														27,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														matrixSizeLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(matrixScrollPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										222,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														modeOneLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														28,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														modeTwoLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														28,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(modeOneBt)
												.addComponent(modeTwoBt))
								.addContainerGap(51, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void modeOneBtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void commitSizeBtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel USTClogo;
	private javax.swing.JButton commitSizeBt;
	private javax.swing.JTable inputMatrixTable;
	private javax.swing.JScrollPane matrixScrollPane;
	private javax.swing.JLabel matrixSizeLabel;
	private javax.swing.JButton modeOneBt;
	private javax.swing.JLabel modeOneLabel;
	private javax.swing.JButton modeTwoBt;
	private javax.swing.JLabel modeTwoLabel;
	private javax.swing.JTextField sizeInput;
	// End of variables declaration//GEN-END:variables

}